kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:alpine
    commands:
      - npm install

  - name: build
    image: node:alpine
    commands:
      - npm run build
      
  - name: deploy
    image: appleboy/drone-rsync
    settings:
      user: yyphksou
      host: /home/yyphksou
      source: directorio_fuente/
      target: directorio_destino/
      key:
        from_secret: ssh_key
